language: objective-c
osx_image: xcode9.2
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift test
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
branches:
  only:
  - master
